### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by robertson-wai** [argman/EAST#100]
Running the demo(http://east.zxytim.com/) with provided demo images is giving 500 Internal Server Error.

**Comment by zxytim** [comment]
Fixed.

**Comment by sudheerachary** [comment]
Running demo give this error **"502 Bad Gateway"**, Please resolve this.

**Comment by zxytim** [comment]
Fixed again.

**Comment by sudheerachary** [comment]
Great, Thanks.
