### ISSUE TITLE
About  full convolution  of coordinates

### ISSUE THREAD

**Issue by ccnankai** [argman/EAST#103]
Hi,  @argman 
When fully convolutional,  multiplied by FLAGS.text_scale, 
https://github.com/argman/EAST/blob/master/model.py#L78
I do not understand why this is done?  Thank you very much.

**Comment by xiaodiu2010** [comment]
Multiplied this factor means the network only need to predict small numbers in range(0,1). This makes it much easier and faster to converge

**Comment by argman** [comment]
Yes, I borrow the idea from another paper, make a restriction will make the network learn more smoothly
