### ISSUE TITLE
Poly in wrong direction during training on the Cursive Text (Written from right to left)

### ISSUE THREAD

**Issue by guddulrk** [argman/EAST#104]
Hi,
I am training this model on cursive text (written from right to left direction). I have set the annotations correctly, but when the training is started, it shows poly in the wrong direction. I have my custom dataset and the images are of different widths and heights. Should I need to make them in the same size?

![train](https://user-images.githubusercontent.com/25378285/36359960-0bcb921e-1574-11e8-9134-fa10631e6988.png)

Thanks

**Comment by ravikantb** [comment]
No, same size images is not required. this error comes when the training dataset contains bounding box coordinates in wrong order. Correct ordering is:
top-left-x, top-left-y, top-right-x, top-right-y, bottom-right-x, bottom-right-y, bottom-left-x, bottom-left-y

**Comment by argman** [comment]
Ravikantb is right

**Comment by guddulrk** [comment]
I have checked, all the images have bounding box coordinates in the same way as shown in training example folder. 
The same dataset works correctly on CTPN.
