### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by BurhanUlTayyab** [argman/EAST#11]
Hi!!!

I have been trying to initiate the training for Arabic Datasets for this model but as soon as try to start it, it gives me this 
"poly in wrong direction "

The dataset consists of 9 values compromising (x0,y0) to (x3, y3) clockwise and one word to describe the selected region.

I am using Tensorflow v1.2 using Python 3.5 and I have successfully initiated the demo on my server.

I request you to please guide me on this issue.

Thanks
Burhan Ul Tayyab

**Comment by argman** [comment]
Thanks for try this on arabic data.
This print is used to debug, because the program assumes your polygon is in clockwise, and if its anticlockwise, the code will reverse it. you can see [line](https://github.com/argman/EAST/blob/master/icdar.py#L109)

And if you get nice results, please inform us!

**Comment by BurhanUlTayyab** [comment]
Sure,

I have tried again to refit it, but it is still the problem for some images it is not the issue, however for other it still persists.

I am drawing a rectangle via keyboard to tell you my coordinates.

(x1,y1)                                                  (x2,y2)
|-------------------------------------------------------|
|                                                                  |
|                                                                  |
|                                                                  |
|-------------------------------------------------------|
(x4,y4)                                                     (x3,y3)


Thanks
Burhan Ul Tayyab

**Comment by argman** [comment]
can you provide a sample text file you used for training ?

**Comment by BurhanUlTayyab** [comment]
Sure

[AljazeeraHD_vd01_frame_18.txt](https://github.com/argman/EAST/files/1217555/AljazeeraHD_vd01_frame_18.txt)

**Comment by argman** [comment]
why there are negative values ? and the coord in your text seems
(x3,y3)                                                  (x3,y3)
^^^^^^^^^^^^
                                                             
^^^^^^^^^^^^
(x2,y2)                                                     (x1,y1)(staring point)

this is strange.

**Comment by BurhanUlTayyab** [comment]
Basically the dataset was taken from AcTiV, and it consisted of x,y,width,height, I manually converted into x1,y1 format. 

The formulas I used are
x1,y1 = x,y
x2,y2 = x-width, y
x3,y3 = x-width, y+height
x4,y4 = x, y+height

Please guide me if there is any mistake in doing all of this

Thanks
Burhan Ul Tayyab

**Comment by argman** [comment]
I think it should be
(x,y)            (x+w,y)
^^^^^^^^^^^^

^^^^^^^^^^^^
(x,y+h)     (x+w,y+h)

**Comment by BurhanUlTayyab** [comment]
Solved

Thank you very Much.
