### ISSUE TITLE
error in process of training：poly in wrong direction

### ISSUE THREAD

**Issue by hanoilu** [argman/EAST#119]
![image](https://user-images.githubusercontent.com/20789917/37655652-dec81a84-2c80-11e8-9bf7-14ab14231657.png)
I have changed the data set to be the same as sample. Why is this prompt?
and the picture and text are also put together, why does the prompt text not exist?

my command：
![image](https://user-images.githubusercontent.com/20789917/37655939-93bdaecc-2c81-11e8-817e-490cbc94e027.png)

**Comment by cltdevelop** [comment]
The order of coordination in txt file is (x1, y1, x2, y2, x3, y3, x4, y4, 'word sample'). This order is clockwise.

**Comment by hanoilu** [comment]
Thank you！My dataset hasn't been processed.
