### ISSUE TITLE
Cannot run eval.py

### ISSUE THREAD

**Issue by eric-tc** [argman/EAST#126]
Hi when i run "python eval.py --test_data_path=/Users/Eric/Desktop/EAST/demo_images/  --checkpoint_path=/Users/Eric/Desktop/east_icdar2015_resnet_v1_50_rbox/ --output_dir=/Users/Eric/Desktop/EAST_detect"
I got the following error

"EAST/lanms/__init__.py", line 12, in merge_quadrangle_n9
   from .adaptor import merge_quadrangle_n9 as nms_impl
ImportError: dynamic module does not define init function (initadaptor)"

How can i resolve this?

Thanks

**Comment by eric-tc** [comment]
ok i have resolved with make clean && make

**Comment by CMWENLIU** [comment]
Hi @eric-tc,
I have the same problem now.
Could you tell me where is 'make clean && make' , and how to 'make clean && make'?
Thanks a lot!
