### ISSUE TITLE
Model Testing Issue

### ISSUE THREAD

**Issue by BurhanUlTayyab** [argman/EAST#13]
Hello !!!

I've successfully trained the model on Arabic dataset, however when I try to test the model, it just returns only the same image as before without any text boxes, can you please help me in that? I've checked the paths again and again and they are correct.

Thanks
Burhan Ul Tayyab

**Comment by argman** [comment]
Can you provide a sample image ? And a sample annotation

**Comment by BurhanUlTayyab** [comment]
It worked!!! I was not passing bounding boxes to rectangle , Thanks by the way!!!! There is one problem, that is I can't get what input_size tells us, can you please specify that???

Thanks
Burhan Ul Tayyab

**Comment by ttywhu** [comment]
@BurhanUlTayyab 
Hi
I just meet the same problem with you，could you tell me how to solve this？

**Comment by BurhanUlTayyab** [comment]
@ttywhu You either have to train more or either bounding boxes are not forming rectangles. First check case 1 and see if your model works on your training dataset.

**Comment by ttywhu** [comment]
@BurhanUlTayyab  I just try the model it gives.

**Comment by argman** [comment]
@BurhanUlTayyab input_size is the size of images used in training, here we assume your text boxes cannot be longer than input_size, you can adapt this according to your situation.

**Comment by BurhanUlTayyab** [comment]
@argman Thanks man!!! I trained it for rectangles that's why results were not that good. Retraining it, and sure I'll show you the result as soon as I'm finished.....
