### ISSUE TITLE
problem 'lams' when run eval.py

### ISSUE THREAD

**Issue by gangliu123** [argman/EAST#132]
g++ verison 4.8.5
Still got problem when execute 'make' for generate '.so'file 
![pro](https://user-images.githubusercontent.com/31200030/38189828-37350130-3651-11e8-8541-f548d140f679.PNG)
Could you guys give me some suggestion? Thanks a lot

**Comment by gangliu123** [comment]
![problem](https://user-images.githubusercontent.com/31200030/38190354-500d6e70-3653-11e8-8d32-f49fd115cd10.PNG)

**Comment by IngleJaya95** [comment]
@gangliu123  How did you resolve it ? I am facing same issue.
