### ISSUE TITLE
How many steps needed for training

### ISSUE THREAD

**Issue by ZXdatascience** [argman/EAST#136]
Hi,

I changed your original model's ResNet backbone to another one and trained the model on a 4 GPU machine. Now, I've trained for 12000 steps with model loss between 0.0015 to 0.003. However, the results is much worse than yours. I'm not sure if it's my model's problem or I didn't train long enough.

Could you please tell me how many steps you take to train your model? Also what's the range of loss at final training steps?

Thanks in advance

**Comment by sabarinathandevanathan** [comment]
could you suggest how many steps and parameters to be changed

**Comment by zhangluustb** [comment]
> Hi,
> 
> I changed your original model's ResNet backbone to another one and trained the model on a 4 GPU machine. Now, I've trained for 12000 steps with model loss between 0.0015 to 0.003. However, the results is much worse than yours. I'm not sure if it's my model's problem or I didn't train long enough.
> 
> Could you please tell me how many steps you take to train your model? Also what's the range of loss at final training steps?
> 
> Thanks in advance

How long did you take for your  12000 steps training? Which one Gpu do you have,1080ti?

**Comment by Gauravchats** [comment]
can you please elaborate why you have considered using 10,000 steps in EAST??
