### ISSUE TITLE
我用training_samples/下的数据训练，很长时间没有反应

### ISSUE THREAD

**Issue by afterimagex** [argman/EAST#137]
Generator use 10 batches for buffering, this may take a while, you can tune this yourself.
2 training images in training_samples/
2 training images in training_samples/
2 training images in training_samples/
2 training images in training_samples/
2 training images in training_samples/
2 training images in training_samples/
2 training images in training_samples/
2 training images in training_samples/
2 training images in training_samples/
2 training images in training_samples/
2 training images in training_samples/
2 training images in training_samples/

到这里我等待了好久，依然没有执行训练

**Comment by xiaodao1990** [comment]
我也遇到了同样的问题，请问你最后怎么解决的呢？

**Comment by xiaodao1990** [comment]
@afterimagex

**Comment by xieyufei1993** [comment]
增加图片的数量，因为batch_size默认设置的是32，训练集得有32张以上
@xiaodao1990

**Comment by 20180821** [comment]
我现在也遇到了跟你一样的问题，请问是哪里出问题了，怎么改正啊，希望得到你的回答
