### ISSUE TITLE
Exporting frozen graph.

### ISSUE THREAD

**Issue by PiotrGrzybowski** [argman/EAST#140]
Hello @argman,

I have a question about exporting checkpoint to frozen_graph.pb. #85 hasn't helped me.

When I exported all nodes to the frozen graph i got the result:
Converted 867 variables to const ops.
39737 ops in the final graph. 

The exported graph size is 378M in compare to model.ckpt-49491.data = 368M.

Is is possible to export just a subset of nodes to get working model after loading exported graph?

**Comment by argman** [comment]
maybe some parameters in your export script is wrong

**Comment by ruiniao** [comment]
@PiotrGrzybowski  have you fixed the problem? I have the similar problem. Help! Thanks!

**Comment by PiotrGrzybowski** [comment]
@ruiniao 

I have left it in that shape.

**Comment by ruiniao** [comment]
@PiotrGrzybowski  could you please share the freeze and inference scripts? Thx! ruiniao@163.com

**Comment by adeelnasrullah94** [comment]
@ruiniao I am facing the same issue. Can you guide me regarding freezing graph?
Thanks

**Comment by Basanti-xian** [comment]
@PiotrGrzybowski @ruiniao after got the pb file, did you have any problem in using it? I got the following error. It could be very helpful if you guys have any advice.

TypeError: Cannot convert a tensor of type float32 to an input of type float32_ref

**Comment by PiotrGrzybowski** [comment]
@Basanti-xian After exporting pb graph it was working fine. Unfortunately I can not give you the script. I do not have access to the repository I used in anymore. Nevertheless I will check if I have any local copy of the script.

**Comment by beiliubei** [comment]
@PiotrGrzybowski 

would you please share me the scripts. Or the output node names? THKS

**Comment by teemiik** [comment]
could you show the script to run the pb file? my mail teemiik@mail.ru. Thanks!

**Comment by xsvonjhs** [comment]
By replacing the code to load checkpoint in `eval.py` I'm able to freeze the graph after running thescript.

Replace with
```
   with tf.gfile.GFile(pb_file, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())

    with tf.Graph().as_default() as graph:
        tf.import_graph_def(
            graph_def,
            name=""
        )

    with tf.Session(graph=graph) as sess:
        init = tf.global_variables_initializer()
        input_images = sess.graph.get_tensor_by_name("input_images:0")
        f_score = sess.graph.get_tensor_by_name('feature_fusion/Conv_7/Sigmoid:0')
        f_geometry = sess.graph.get_tensor_by_name('feature_fusion/concat_3:0')
```

**Comment by xsvonjhs** [comment]
I've successfully export a usable frozen graph by inserting following code into `eval.py`
```
           output_graph_def = tf.graph_util.convert_variables_to_constants(
                sess, # The session is used to retrieve the weights
                tf.get_default_graph().as_graph_def(), # The graph_def is used to retrieve the nodes 
                ["feature_fusion/Conv_7/Sigmoid","feature_fusion/concat_3"]
            ) 

            with tf.gfile.GFile(output_graph, "wb") as f:
                f.write(output_graph_def.SerializeToString())
            print("%d ops in the final graph." % len(output_graph_def.node))
```

**Comment by teemiik** [comment]
I also figured out how to do it! here is rewritten by me eval.py function main

`def main(argv=None):
    import os
    os.environ['CUDA_VISIBLE_DEVICES'] = FLAGS.gpu_list

    try:
        os.makedirs(FLAGS.output_dir)
    except OSError as e:
        if e.errno != 17:
            raise

    print("load_graph")
    graph = load_graph(FLAGS.checkpoint_path)

    input_images = graph.get_tensor_by_name(
        'import/input_images:0')
    
    f_score = graph.get_tensor_by_name('import/feature_fusion/Conv_7/Sigmoid:0')
    f_geometry = graph.get_tensor_by_name(
        'import/feature_fusion/concat_3:0')

    with tf.Session(graph=graph) as sess:

        im_fn_list = get_images()
        for im_fn in im_fn_list:
            im = cv2.imread(im_fn)[:, :, ::-1]
            start_time = time.time()
            im_resized, (ratio_h, ratio_w) = resize_image(im)

            timer = {'net': 0, 'restore': 0, 'nms': 0}
            start = time.time()

            file_writer = tf.summary.FileWriter('tmp/log', sess.graph)            

            score, geometry = sess.run([f_score, f_geometry], feed_dict={
                                        input_images: [im_resized]})
            timer['net'] = time.time() - start

            boxes, timer = detect(score_map=score, geo_map=geometry, timer=timer)
            print('{} : net {:.0f}ms, restore {:.0f}ms, nms {:.0f}ms'.format(
                im_fn, timer['net']*1000, timer['restore']*1000, timer['nms']*1000))

            if boxes is not None:
                boxes = boxes[:, :8].reshape((-1, 4, 2))
                boxes[:, :, 0] /= ratio_w
                boxes[:, :, 1] /= ratio_h

            duration = time.time() - start_time
            print('[timing] {}'.format(duration))

            # save to file
            if boxes is not None:
                res_file = os.path.join(
                    FLAGS.output_dir,
                    '{}.txt'.format(
                        os.path.basename(im_fn).split('.')[0]))

                with open(res_file, 'w') as f:
                    for box in boxes:
                        # to avoid submitting errors
                        box = sort_poly(box.astype(np.int32))
                        if np.linalg.norm(box[0] - box[1]) < 5 or np.linalg.norm(box[3]-box[0]) < 5:
                            continue
                        f.write('{},{},{},{},{},{},{},{}\r\n'.format(
                            box[0, 0], box[0, 1], box[1, 0], box[1, 1], box[2, 0], box[2, 1], box[3, 0], box[3, 1],
                        ))
                        cv2.polylines(im[:, :, ::-1], [box.astype(np.int32).reshape((-1, 1, 2))], True, color=(255, 255, 0), thickness=1)
            if not FLAGS.no_write_images:
                img_path = os.path.join(FLAGS.output_dir, os.path.basename(im_fn))
                cv2.imwrite(img_path, im[:, :, ::-1])`

**Comment by a41888936** [comment]
@teemiik Thanks you for sharing. 'load_graph' in your code is customized function???

**Comment by teemiik** [comment]
@a41888936 Yes

def load_graph(frozen_graph_filename):
    # We load the protobuf file from the disk and parse it to retrieve the
    # unserialized graph_def
    with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())

    # Then, we import the graph_def into a new Graph and returns it
    with tf.Graph().as_default() as graph:
        # The name var will prefix every op/nodes in your graph
        # Since we load everything in a new graph, this is not needed
        tf.import_graph_def(graph_def)
    return graph

**Comment by mohammedayub44** [comment]
@ruiniao  @teemiik  Can you share the right way to freezing the graph. Even though this is an old issue, look like it persists. The frozen graph I have (using @xsvonjhs solution) does not give good results. Did you happen to use `ExponentialMovingAverage` as proposed by folks in other issues.?
