### ISSUE TITLE
Cannot compile lanms

### ISSUE THREAD

**Issue by frozenscrypt** [argman/EAST#145]
I've been trying to run the system on windows 7. When I run the code the output is:

Traceback (most recent call last):
  File "eval.py", line 9, in <module>
    import lanms
  File "C:\Project\EAST\lanms\__init__.py", line 9, in <module>
    raise RuntimeError('Cannot compile lanms: {}'.format(BASE_DIR))
RuntimeError: Cannot compile lanms: C:/Project/EAST/lanms/

**Comment by loulan-D** [comment]
I try to run the system on Ubuntu . 
But i cannot complie lanms.
How  do you deal with the problems? Can you tell me ? Thank you .

**Comment by frozenscrypt** [comment]
Was able to run it on Windows. The solution at the end of the page worked!
