### ISSUE TITLE
I cannot train with larger input with larger input_size and text_scale.

### ISSUE THREAD

**Issue by tianzhuotao** [argman/EAST#153]
Two args are used for adjusting input size : input_size and text_scale which should match each other.

However, when trying to increase recall by training with larger input images (set input_size and text_scale both to 640, rather than 512), I got the result where all predicted bounding boxes were centered at the text area as the pictures show.

I have checked the shrink_poly function and set the shrink ratio R to 0.1 or even smaller, but nothing changed.

Can anyone help me solve this problem ?
![image](https://user-images.githubusercontent.com/13251183/39808355-49b2a2e0-53b1-11e8-895a-0ccba7c6dd62.png)
![image](https://user-images.githubusercontent.com/13251183/39808382-5c61e4c8-53b1-11e8-9b4a-726fa9dcec95.png)
![image](https://user-images.githubusercontent.com/13251183/39808406-6ca5dd08-53b1-11e8-8adf-aecbad87db4d.png)

**Comment by Yuanhang8605** [comment]
The textscale should keep constant in different input scale,  because the receptive field of the convolve kernel is fixed.

**Comment by tianzhuotao** [comment]
@Yuanhang8605  thanks   ~

**Comment by xieyufei1993** [comment]
I set the input_size = 512 and text_scale=512, i meet this problem, how can i solve it ?just increase the text_scale to 768？

![image](https://user-images.githubusercontent.com/19235054/44647476-bbb1f200-aa10-11e8-9e6a-214f67950020.png)
@tianzhuotao @Yuanhang8605 @zxytim @argman

**Comment by tianzhuotao** [comment]
@xieyufei1993 this problem is due to the model itself's limitation. The boundary distance regression is insufficient to cover long text areas.

**Comment by tianzhuotao** [comment]
@xieyufei1993 Of course you can try increasing the text scale to 768, but the insreacement to 768 on input size is also needed, otherwise the text scale (768) makes no sense.
