### ISSUE TITLE
Result not reproducible for ICDAR2015

### ISSUE THREAD

**Issue by dajiangxiaoyan** [argman/EAST#159]
Hi,
I'm trying to reproduce the result in the paper. But it seems not reproducible.
![image](https://user-images.githubusercontent.com/17979833/40601659-9e65b35a-6288-11e8-9cec-6cd47fbc5f8f.png)

I am using the pre-trained model downloaded from your link which is for ICDAR2015 (east_icdar2015_resnet_v1_50_rbox)

And for the evaluation,
I'm using the official evaluation code downloaded from ICDAR challenge

And below is the tested set link

[ICDAR Challenge 4 task1 aka ICDAR2015 task 1 TESTSET](http://rrc.cvc.uab.es/?com=downloads&action=download&ch=&f=aHR0cDovL3JyYy5jdmMudWFiLmVzLz9jb209ZG93bmxvYWRzJmFjdGlvbj1kb3dubG9hZCZmaWxlPWNoNF90ZXN0X2ltYWdlcy56aXA=)

But i got a very bad result, far away from f1-score 80%
![image](https://user-images.githubusercontent.com/17979833/40601787-105ede00-6289-11e8-91f2-3e470ee95963.png)

Please help if there are another parameters to be tuned.

**Comment by xylcbd** [comment]
any reason be found now?
