### ISSUE TITLE
Using my own dataset to train the model

### ISSUE THREAD

**Issue by dandiao190** [argman/EAST#16]
Hi, @argman 
    I want to train the model using my own dataset, what can I do for this?
    How to create the gt text files? And what's the each parameter stands for?

**Comment by argman** [comment]
You can prepare your dataset like icdar2015. see http://rrc.cvc.uab.es/?ch=4&com=tasks for details.

**Comment by dandiao190** [comment]
Hi, @argman
I searched the pages, but I cann't find a tool to generate the gt text files. Could you provide one for me? thx

**Comment by argman** [comment]
You can see the examples in training_examples/ folder, and generate yourself.

**Comment by dandiao190** [comment]
@argman  Thank you for your answer.
I find some tools to do the text labling work. But most of them only provide xmin, ymin, xmax, ymax, transcation, without considering the rotation of text. I've got a variety of images, it will takes me a lot of time to lable the image comparing with scaling. Is there a convient way to do these. Wish your reply, thank you.

**Comment by argman** [comment]
you should find some tool be able to label polygons rather than rectangles. I think there are some open source labeling tools.

**Comment by dandiao190** [comment]
@argman, I find the VGG Image Annotator which can lable both polygons and rectangles, thanks a lot.

**Comment by InesBeltaief** [comment]
hey @dandiao190 could you please share the annotation process you used ?

**Comment by 20180821** [comment]
> @argman，我找到了VGG图像注释器，它可以兼容多边形和矩形，非常感谢。

你好，我现在也想参考icdar2015的数据集标注自己的数据但是我不会，能分享一下怎么制作标签嘛，非常感谢，希望得到您的回复

**Comment by 20180821** [comment]
> 嘿@dandiao190你能分享一下你用过的注释过程吗？

你好，我现在也想参考icdar2015的数据集标注自己的数据但是我不会，能分享一下怎么制作标签嘛，非常感谢，希望得到您的回复
