### ISSUE TITLE
this project can't run on  win10? my os : win10,python3.6,tensorflow1.5.0 

### ISSUE THREAD

**Issue by ds-gong** [argman/EAST#170]
H:\DL\EAST\EAST-master>python eval.py --test_data_path=/tmp/images/ --gpu_list=0 --checkpoint_path=/east_icdar2015_resnet_v1_50_rbox/ --output_dir=/tmp/save
C:\Program Files\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
BASE_DIR: H:\DL\EAST\EAST-master\lanms
Traceback (most recent call last):
  File "eval.py", line 9, in <module>
    import lanms
  File "H:\DL\EAST\EAST-master\lanms\__init__.py", line 8, in <module>
    if subprocess.call(['make', '-C', BASE_DIR]) != 0:  # return value
  File "C:\Program Files\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by fsluckymao** [comment]
+1

**Comment by yyttmonster** [comment]
+1

**Comment by tajir0** [comment]
+2

**Comment by AlexanderMakarov95** [comment]
Experiencing the same issue! 

[Win Error 2] The system cannot find the file specified.

Any help would be appreciated.

**Comment by 245336090** [comment]
+1

**Comment by aztbzkrt** [comment]
Experiencing the same issue too. Did you solve the issue?

**Comment by chensiyuanlove** [comment]
+4
