### ISSUE TITLE
Results on Arabic and Urdu Datasets

### ISSUE THREAD

**Issue by BurhanUlTayyab** [argman/EAST#18]
Hello Argman!!!!

Hope that you are in your finest health, here are some of the results, trained on Arabic Dataset

![23](https://user-images.githubusercontent.com/25680088/29600746-2dbb6356-87f1-11e7-9dde-915d6d20040f.png)

![24](https://user-images.githubusercontent.com/25680088/29600752-34ad690c-87f1-11e7-961e-31e8b322f2f4.png)

Basically, what our main purpose was to detect Urdu News-Tickers, therefore I'm sending you those too.

![output 7](https://user-images.githubusercontent.com/25680088/29600771-514516c8-87f1-11e7-8cf1-8aae21de3cde.png)

![output 5](https://user-images.githubusercontent.com/25680088/29600777-5a5a5d04-87f1-11e7-9091-5775c2a16605.png)

![output 4](https://user-images.githubusercontent.com/25680088/29600779-5f49bd1e-87f1-11e7-8686-a93e7c328be2.png)

![output 3](https://user-images.githubusercontent.com/25680088/29600786-64bfd1ca-87f1-11e7-89b3-cff0d0999a55.png)

![output 2](https://user-images.githubusercontent.com/25680088/29600797-7240a31a-87f1-11e7-84c1-e100bf8d9ec2.png)

![output 1](https://user-images.githubusercontent.com/25680088/29600806-871ec6c2-87f1-11e7-879d-6c4103fbd93b.png)

You can use the photos anyway you want, just cite my github link.

Anyway I can also give you the model if you want!!!!

Thanks Again
Burhan Ul Tayyab

**Comment by rmmal** [comment]
Did you use a private dataset for arabic text detection ? any details about it ?
can u give me your email ?

**Comment by BurhanUlTayyab** [comment]
I used AcTiV Detection Dataset, my email is: btayyab.bese15seecs@seecs.edu.pk
