### ISSUE TITLE
Problem with run in Windows: No such file or directory: '/proc/cpuinfo'

### ISSUE THREAD

**Issue by zqm840527** [argman/EAST#184]
I am using windows 7, so I followed 
https://github.com/argman/EAST/issues/120 
to make it run in windows.

But when I run the demo server, a problem occurred "FileNotFoundError: [Errno 2] No such file or directory: '/proc/cpuinfo'"

And I googled it and found "/proc/cpuinfo" is only for Linux or Linux-like systems, so when using windows, the mentioned problem will show up.

Could anyone help me to solve that? Thank you.  

@argman @zxytim @ZhuMingmin9123
-------------------------------------------------------------------------------
In browser:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

--------------------------------------------------------------------------------
(base) C:\Users\zqm>cd/

(base) C:\>e:

(base) E:\>cd E:\EAST_ICPR-master

(base) E:\EAST_ICPR-master>python run_demo_server.py --checkpoint_path=E:\EAST_I
CPR-master/tmp/east_icdar2015_resnet_v1_50_rbox/
 * Serving Flask app "run_demo_server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8769/ (Press CTRL+C to quit)
127.0.0.1 - - [31/Aug/2018 00:22:04] "[37mGET / HTTP/1.1[0m" 200 -
e:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of
 the second argument of issubdtype from `float` to `np.floating` is deprecated.
In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
resnet_v1_50/block1 (?, ?, ?, 256)
resnet_v1_50/block2 (?, ?, ?, 512)
resnet_v1_50/block3 (?, ?, ?, 1024)
resnet_v1_50/block4 (?, ?, ?, 2048)
Shape of f_0 (?, ?, ?, 2048)
Shape of f_1 (?, ?, ?, 512)
Shape of f_2 (?, ?, ?, 256)
Shape of f_3 (?, ?, ?, 64)
Shape of h_0 (?, ?, ?, 2048), g_0 (?, ?, ?, 2048)
Shape of h_1 (?, ?, ?, 128), g_1 (?, ?, ?, 128)
Shape of h_2 (?, ?, ?, 64), g_2 (?, ?, ?, 64)
Shape of h_3 (?, ?, ?, 32), g_3 (?, ?, ?, 32)
162 text boxes before nms
[2018-08-31 00:22:37,630] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "e:\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatc
h_request
    rv = self.handle_user_exception(e)
  File "e:\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_
exception
    reraise(exc_type, exc_value, tb)
  File "e:\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "e:\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatc
h_request
    rv = self.dispatch_request()
  File "e:\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_req
uest
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run_demo_server.py", line 204, in index_post
    rst = get_predictor(checkpoint_path)(img)
  File "run_demo_server.py", line 136, in predictor
    ret.update(get_host_info())
  File "run_demo_server.py", line 23, in get_host_info
    with open('/proc/cpuinfo') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/cpuinfo'
127.0.0.1 - - [31/Aug/2018 00:22:37] "[1m[35mPOST / HTTP/1.1[0m" 500 -

**Comment by harshthaker** [comment]
Getting the same error. Looking for the solution.

**Comment by zqm840527** [comment]
@harshthaker 

Wonderful! It works for me as well, many thanks!
