### ISSUE TITLE
May be some error in locality_aware_nms.py

### ISSUE THREAD

**Issue by facetohard** [argman/EAST#19]
In the line 68 of locality_aware_nms.py, you have writen:
`return standard_nms(np.array(polys), thres)`
However, in the paper, the author wrote that:
`return STANDARDNMS(S)`
Does it has better performance or is just an error?

**Comment by zxytim** [comment]
The algorithm illustrated in the paper is just to show the idea, not an
exact implementation. Standard NMS by definition need an IoU threshold.
Likewise, the SHOULD-MERGE function in the paper should also get a
threshold parameter if it fully conform to the implementation, however,
actually it does not.

**Comment by facetohard** [comment]
In the function of `nms_locality`, you processed the variable `polys` and got the result `S`. However the return of this function is about `polys`. I means whether there should be:
`standard_nms(np.array(S), thres)`.

**Comment by zxytim** [comment]
I consider it a mistake. @argman will you please take a look at it?

**Comment by argman** [comment]
@facetohard its a mistake.., forget to change that when experiment.
