### ISSUE TITLE
Error occurs when trying eval.py

### ISSUE THREAD

**Issue by BYJRK** [argman/EAST#20]
When trying to use the `eval.py`, error occurs, and it looks like the `adaptor.so` may have something wrong (e.g. complied by not suitable g++). I'm using g++ 5.4.0

The error report is like this:

```
Find 1 images
40795 text boxes before nms
Traceback (most recent call last):
  File "eval.py", line 194, in <module>
    tf.app.run()
  File "/home/aqua/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 160, in main
    boxes, timer = detect(score_map=score, geo_map=geometry, timer=timer)
  File "eval.py", line 98, in detect
    boxes = lanms.merge_quadrangle_n9(boxes.astype('float32'), nms_thres)
  File "/home/aqua/EAST/lanms/__init__.py", line 12, in merge_quadrangle_n9
    from .adaptor import merge_quadrangle_n9 as nms_impl
ImportError: /home/aqua/EAST/lanms/adaptor.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm
```

Can you help me fix it?

**Comment by facetohard** [comment]
You may enter:
`/path/to/your/EAST/lanms`
and then excute
`make`

**Comment by BYJRK** [comment]
Emm... I’m pretty sure I’ve already done this before. At least I can see the .so file there.

**Comment by BYJRK** [comment]
I think I get it. Only `g++-4.8` can compile the `.so` file correctly to be imported. `4.7` or `4.9` cannot.

**Comment by facetohard** [comment]
which system do you use? I have trained ICADR2015 dataset on Ubuntu 16.04 which the version of g++ is 5.4.
I thought that the code is only compatible with python3.

**Comment by BYJRK** [comment]
`Ubuntu 16.04`, the original `g++` is `5.4`, and after I changed to `4.8`, it finally works (since it needs `C++ 11`, so `4.7` is not suitable). Also I'm using `Anaconda 3`, `python 3.5`.

**Comment by PallawiSinghal** [comment]
k ,i have solved this problem. I modify the file lanms/Makefile ,change the python3-config to python-config
