### ISSUE TITLE
About the python version

### ISSUE THREAD

**Issue by ZumingHuang** [argman/EAST#22]
It seems that we should use tensorflow with python3.x to support lanms, which is a process in eval.py. Is it possible for us to use tensorflow with python2.7 to run eval.py?

Thanks.

**Comment by argman** [comment]
If you donot care about speed, then you can use nms of python version, then 2 or 3 should be both ok.

**Comment by ZumingHuang** [comment]
Okay. I have tried to use nms of python version. It works fine.

Thank you.

**Comment by dotsonliu** [comment]
@ZumingHuang how you do it? use python2.7?

**Comment by ccnankai** [comment]
@ZumingHuang  @argman  @dotsonliu    how  can  I use nms of python version,Is there a python version of the code? thank you very much.

**Comment by StephenChen625** [comment]
@ccnankai  @dotsonliu 
Just comment the line " boxes = lanms.merge_quadrangle_n9(boxes.astype('float32'), nms_thres) " in the detect method, and uncomment the line before,which is " boxes = nms_locality.nms_locality(boxes.astype(np.float64), nms_thres)".

Then you can use the python2.7 to run eval.py.
It works for me. So I hope it will be helpful.

**Comment by StephenChen625** [comment]
First we should comment the line "import lanms", of course.
