### ISSUE TITLE
How to build the model frozen

### ISSUE THREAD

**Issue by pitchayakit** [argman/EAST#224]
Hello, during train the model I don't know how to build the model frozen anyone please help or guide

**Comment by shahmustafa** [comment]
HI, To freeze model and using it with python, follow this blog by [morgan](https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc)

**Comment by pitchayakit** [comment]
I tried and have got this error "AssertionError: freeze is not in graph"
