### ISSUE TITLE
inference using frozen pb file can not gets the same result in contrast to original ckpt 

### ISSUE THREAD

**Issue by IvyGongoogle** [argman/EAST#225]
hello,  After I use your code to train a `ckpt` model. I try two methods for inference:
> 1. use `eval.py` to infer this `ckpt` model.
> 2. use below code to freeze the trained ckpt model and meta to a single pb file:
```
import cv2
import time
import math
import os
from skimage import io
import numpy as np
import tensorflow as tf
from PIL import Image
import locality_aware_nms as nms_locality
import lanms
import copy
import model

tf.app.flags.DEFINE_string('gpu_list', '0', '')
tf.app.flags.DEFINE_string('checkpoint_path', './east_resnet_v1_50_rbox/','')
tf.app.flags.DEFINE_string('meta', './east_resnet_v1_50_rbox/model.ckpt-4412.meta','')
tf.app.flags.DEFINE_string('output_dir', './output/', '')
FLAGS = tf.app.flags.FLAGS

def freeze():
    os.environ['CUDA_VISIBLE_DEVICES'] = FLAGS.gpu_list
    input_images = tf.placeholder(tf.float32, shape=[None, None, None, 3], name='input_images')
    global_step = tf.get_variable('global_step', [], initializer=tf.constant_initializer(0), trainable=False)

    f_score, f_geometry = model.model(input_images, is_training=False)

    config = tf.ConfigProto(allow_soft_placement=True)

    with tf.Session(config = config) as sess:
        sess.run(tf.global_variables_initializer())
        for op in sess.graph.get_operations():
            # print op
            print op.name

        variable_averages = tf.train.ExponentialMovingAverage(0.997, global_step)
        saver = tf.train.Saver(variable_averages.variables_to_restore())
        # print variable_averages.variables_to_restore()

        ckpt = tf.train.latest_checkpoint(FLAGS.checkpoint_path)
        if ckpt:
            saver.restore(sess, ckpt)
            print("restore from the checkpoint {0}".format(ckpt))

        output_node_names =["feature_fusion/Conv_7/Sigmoid"]

        # Freeze the graph
        frozen_graph_def = tf.graph_util.convert_variables_to_constants(
            sess,
            sess.graph_def,
            output_node_names)
        tf.graph_util.remove_training_nodes(frozen_graph_def)

        # Save the frozen graph
        with open(FLAGS.output_dir+'east_ckpt-4412.pb', 'wb') as f:
          f.write(frozen_graph_def.SerializeToString())

if __name__ == '__main__':
    freeze()
```
then use this frozen `pb` file to infer it.

I find the result of 1 and 2 methods  are still different.
where I make a mistake?
can you give some advises?

**Comment by IvyGongoogle** [comment]
I find the reason. 
Close this issue.

**Comment by shokou-chin** [comment]
Hi @IvyGongoogle ,

I'm interested how you solve the issus.

Because I have a similar problem that I export the `ckpt` to a `SavedModel`.

I can't get same results by passing the same input data to  both  `ckpt` and `SavedModel`.

**Comment by IamMegatron2025** [comment]
@shokou-chin check your code that if you frozen the params with  `ExponentialMovingAverage`

**Comment by tsangsea** [comment]
i have the same problem, and tried lots of solutions including the above, but the problem remains the same, could you show your solution more detail please, or give me a copy of you final converting code? @IvyGongoogle

**Comment by SpringRainLu** [comment]
i also have the same problems using east in opencv.dnn. could show your solution
@IvyGongoogle @tsangsea

**Comment by IamMegatron2025** [comment]
@tsangsea  @SpringRainLu  check your code that if you frozen the params with `ExponentialMovingAverage` value

**Comment by SpringRainLu** [comment]
can you be more specific about the `ExponentialMovingAverage` value
```
variable_averages = tf.train.ExponentialMovingAverage(0.997, global_step)
saver = tf.train.Saver(variable_averages.variables_to_restore())
```
What changes do I need to make in this?
great thanks @IvyGongoogle

**Comment by IamMegatron2025** [comment]
@SpringRainLu  when you train your model with `ExponentialMovingAverage`, then you should use this `ExponentialMovingAverage` value when you do an inference, so that you use the same parameter. Try it.

**Comment by tsangsea** [comment]
it does not work, i've checked several times
