### ISSUE TITLE
Dice loss doesn't descend?

### ISSUE THREAD

**Issue by xijunjun** [argman/EAST#238]
Thanks for reimplementation of EAST!It helps me a lot.Now i am trying to modify it to mxnet,and  use it to detect license plate,but the result is not so good, when i  train the network,the dice loss almost does not descend,and the geo loss will descend.Does someone have the same questions?

**Comment by yuxiaomu** [comment]
@xijunjun 我也有同样的问题，loss从开始就是20几，训练到五万轮都是徘徊在20，请问你后来怎么处理的

**Comment by xijunjun** [comment]
@1810325 后来我优化算法使用adam可以收敛了
