### ISSUE TITLE
how to explain the code  "im = cv2.imread(im_fn)[:, :, ::-1]"  in eval.py, line153？

### ISSUE THREAD

**Issue by clw5180** [argman/EAST#240]
I know cv2.imread() 's output format is (W,H,C), such as 1024*768*3, but why to inverse the order of RGB channel(by using ::-1) ? Here is the code around line 153 in eval.py:
'''
       im_fn_list = get_images()
            for im_fn in im_fn_list:
                im = cv2.imread(im_fn)[:, :, ::-1]
                start_time = time.time()
                im_resized, (ratio_h, ratio_w) = resize_image(im)

                timer = {'net': 0, 'restore': 0, 'nms': 0}
                start = time.time()
                score, geometry = sess.run([f_score, f_geometry], feed_dict={input_images: [im_resized]})
                timer['net'] = time.time() - start

                boxes, timer = detect(score_map=score, geo_map=geometry, timer=timer)
                print('{} : net {:.0f}ms, restore {:.0f}ms, nms {:.0f}ms'.format(
                    im_fn, timer['net']*1000, timer['restore']*1000, timer['nms']*1000))

'''
Can anyone tell me the reason? Thanks a lot!

**Comment by YoadTew** [comment]
cv2 imread reads the image as BGR in default, so the code changes it to RGB

**Comment by clw5180** [comment]
> cv2 imread reads the image as BGR in default, so the code changes it to RGB

Thank you bro!
