### ISSUE TITLE
Am I doing right? 

### ISSUE THREAD

**Issue by GodOfSmallThings** [argman/EAST#25]
I changed loss function and tried to train data through EAST. However, when I tried it and look how training was going on, I found something weird.

![image](https://user-images.githubusercontent.com/20166060/30019536-e2f26996-919b-11e7-8849-1fab965955a6.png)

![image](https://user-images.githubusercontent.com/20166060/30019553-f702e9d8-919b-11e7-8e79-50f7ed97113e.png)

Above pictures are input data and corresponding score map. Shouldn't gt area be black and elsewhere white, rather than the picture? (In picture, gt area is white and elsewhere black)

**Comment by argman** [comment]
You can check whether it is equal to 1

**Comment by GodOfSmallThings** [comment]
How can I check that? I thought that values of gt are black because i thought it would be 1... but the picture, it seems like values of gt are 0 because its white...

**Comment by argman** [comment]
Where did you get your picuture ? You can use tensorboard.
