### ISSUE TITLE
Questions about restore_rectangle_rbox

### ISSUE THREAD

**Issue by rolai** [argman/EAST#26]
The function `restore_rectangle_rbox` in icdar.py is so complicate that after spent a lot time to read and study it, but I still can't understand it!  Could you provide more information or comments about this function?

**Comment by argman** [comment]
It's just a vector implementation, you can think of the process of restore one polygon first.

**Comment by ccnankai** [comment]
@rolai  
Why does xy_text[:,::-1] multiply by 4 ?     line 89  in eval.py
