### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by rmmal** [argman/EAST#29]
I have a dataset that has 12982 images 
when i started training it , i used 24 reader but all what i see is 

) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:23:00.0)
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/
12982 training images in /media/rmmal/data/East_data/

and the gpu utilization is 95% and all the 24 core are 100%

it has been 1 hour till now and nothing changed ?

so is there any thing wrong happened ?

**Comment by argman** [comment]
I dont know, can you provide a training sample or you can check you annotations, see samples in training_samples/

**Comment by rmmal** [comment]
it stuck alot in sleep(0.01)

I had a dataset that has x1,y1,x2,y2 and it's all about 1 class
so i converted it to
x1,y1,x2,y1,x2,y2,x1,y2 ,class1


for each image it may go through sleep(0.01) alot of times between reading the image in the generator function and the end of this function

what could be wrong ?

also i have a GPU that has 6GB ram would it be a problem ?

**Comment by argman** [comment]
you may try to reduce the number of readers and batch size

**Comment by InesBeltaief** [comment]
hello @rmmal can you please share the code that you used to convert annotations?

**Comment by ChuhuiX** [comment]
same problem! may i know if you have solved it and how? thanks!

**Comment by yangxuehang** [comment]
@rmmal  hello, how did you fix the problem about sleep(0.01) ?

**Comment by rmmal** [comment]
@InesBeltaief  if you have x1 , y1 , x2 , y2
then you can write them in such format
file_write.write(x1+","+y1+","+x2+","+y1+","+x2+","+y2+","+x1+","+y2+",text\n")

**Comment by rmmal** [comment]
@yangxuehang  there was a problem in my paths and dataset

**Comment by sdsy888** [comment]
@rmmal @argman Hi, have you fix the stuck problem?

I've already trained some models using this code. However, when I try to train on another server, I encountered the same problem like above.

After showing this:

```bash
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
1029 training images in /ssd/ysong/dataset/icdar15/ch4_training_images
```

It stuck here forever which never happened before. 

I used the same dataset like before(that succeeded in training on other machine), also the same configuration with the server before.

What could be the problem? 
Thank you.
