### ISSUE TITLE
can I run it on CPU mode ? I have no GPU devices 

### ISSUE THREAD

**Issue by InesBeltaief** [argman/EAST#30]

**Comment by argman** [comment]
Yes you can

**Comment by InesBeltaief** [comment]
hello @argman thnx for replying !  could you please help me make the changes needed to run it on cpu mode  ;
I'm a kind of beginner to machine learning and tensorflow :/

**Comment by argman** [comment]
I think you can follow the tutorials of tensorflow and you will  learn a lot.
