### ISSUE TITLE
Cannot compile lanms

### ISSUE THREAD

**Issue by kjanjua26** [argman/EAST#32]
I have .jpg images in the folder, I trying to run eval.py, I have trained the model and have checkpoint file. 
The command I am using is: python3 eval.py --test_data_path=/home/kamranjanjua/EAST/icdarData/ --gpu_list=0 --checkpoint_path=/modelse/ --output_path=/home/kamranjanjua/EAST/output_icdar/

icdarData folder contains the images. 

However, when I run it, the error I get is: raise RuntimeError('Cannot compile lanms: {}'.format(BASE_DIR))

Any solution?

**Comment by argman** [comment]
you should do make in  lanms/
