### ISSUE TITLE
how to get the SavedModel?

### ISSUE THREAD

**Issue by kiss90** [argman/EAST#329]
I have restored the model from checkpoint and saved it as SavedModel. 
However, the saved model doesn't contain the LANMS step. I want to pack all the trained model and LANMS post-processing together. Maybe I need to rewrite the detect function in eval.py to replace the numpy operation with tensor? 
Any advice or suggestions will be appreciated. Thanks in advance!

**Comment by fengxin619** [comment]
how did you do ?  change the ckpt to savedmodel?    can you share the code?

**Comment by ghost** [comment]
https://github.com/argman/EAST/issues/303
