### ISSUE TITLE
Does `from icdar import restore_rectangle`  need so much time?

### ISSUE THREAD

**Issue by facetohard** [argman/EAST#33]
I run the `python3 eval.py`, or `python3 run_demo_server.py`, it will run `from icdar import restore_rectangle`. However, the terminal show that `1000 training images in ./data/train/` and then it may load these training image and it has taken so much time. Does anybody has the same situation?

**Comment by yangxuehang** [comment]
@facetohard  hello, how did you deal with the problem you mentioned above?  Thank you.

**Comment by facetohard** [comment]
Sorry for late response. I download the code again and it works.
