### ISSUE TITLE
the pre-train model can't achieve 80% F1-score.

### ISSUE THREAD

**Issue by zyxunh** [argman/EAST#34]
I run the east_icdar2015_resnet_v1_50_rbox model/model.ckpt-49491 on ICDAR2015-TRW public_test_data, then test the result with the detection_eval_tool but only get 0.4697 F1-score. I don't know what wrong in it.

**Comment by facetohard** [comment]
I met some problem when I test the pre-train model. Could I send you e-mail to ask question?

**Comment by zyxunh** [comment]
@facetohard of course, what is the problem with you, first i think you should use python3 not python2.

**Comment by argman** [comment]
Do you make any changes?

**Comment by zyxunh** [comment]
@argman I have not changed any configuration, but I figure out what happened. I get a fake ICDAR 2015 Competition datasets from http://icdar2015.imageplusplus.com/#Introduction which almost is chinese characters.

**Comment by zyxunh** [comment]
@argman I download the real icdar2015 dataset from http://rrc.cvc.uab.es/?ch=4&com=downloads, but these are some warning when I train the model with icdar2015_data_set, can I ignore this warn? 
Cross point does not exist
Traceback (most recent call last):
  File "/home/yxzh/mount_2/project/ocr/east_yxzh/icdar.py", line 672, in generator
    score_map, geo_map, training_mask,pool_map = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/yxzh/mount_2/project/ocr/east_yxzh/icdar.py", line 533, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/yxzh/mount_2/project/ocr/east_yxzh/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

**Comment by argman** [comment]
yes

**Comment by yaya325** [comment]
I met the same question ,can anybody solve it now?
