### ISSUE TITLE
Is there an option to not rotate bounding boxes?

### ISSUE THREAD

**Issue by s-truax** [argman/EAST#353]
Currently, EAST can draw rotated bounding boxes. Is there a built-in option to opt for EAST to draw a non-rotated bounding box instead of a rotated one?

**Comment by daniiki** [comment]
Did you find a solution to so this?

**Comment by s-truax** [comment]
@daniiki You can convert a polygon `[x1, y1, x2, y2, ..., x_n, y_n]` to a bounding rectangle by doing `[min_of_xs, min_of_ys, max_of_xs, max_of_ys]`
