### ISSUE TITLE
cannot detect single char

### ISSUE THREAD

**Issue by cbzeng110** [argman/EAST#36]
![aa_1](https://user-images.githubusercontent.com/28328930/30358994-62eba6a0-987a-11e7-8bd4-ecdbf80cc773.jpg)

I run the eval.py to detect text. But all the single digit number in this image cannot be detected. Could someone tell me why? thanks

**Comment by arsalan993** [comment]
I am facing the same issue .. 
Surprisingly this thread was marked close without any solution @argman

**Comment by arsalan993** [comment]
Btw bro did you came to any solution to this problem of not detecting single character

**Comment by codecolony** [comment]
Single characters are filtered out during data loading part. You can find out the relevant code where it is done and control it accordingly but it introduces serious performance issues.
