### ISSUE TITLE
您好，我用MSRA-TD500 数据在运行 east模型，报错如下，请问是什么原因？是数据的原因吗？

### ISSUE THREAD

**Issue by dotsonliu** [argman/EAST#38]
数据格式如下：
![image](https://user-images.githubusercontent.com/28289146/30376283-3f6979ac-98be-11e7-885f-ba11ccc8bc5f.png)

![image](https://user-images.githubusercontent.com/28289146/30376294-4972ba8a-98be-11e7-8efb-5c55a5665f4f.png)

![image](https://user-images.githubusercontent.com/28289146/30376307-5285628a-98be-11e7-969c-65440e56280b.png)

![image](https://user-images.githubusercontent.com/28289146/30376218-0fc29c9c-98be-11e7-9570-5e3e1949a395.png)

**Comment by db2010** [comment]
楼主，您好，我想请教下在windows下您如何编译lnms这个模块的，在def get_predictor(checkpoint_path)
   有 import lanms，而在lnms文件夹下的makefile是linux的，你是如何在windows下编译成功的呢？感谢！

**Comment by argman** [comment]
@dotsonliu , See readme for training data format.

**Comment by BYJRK** [comment]
In the script `icdar.py`, there is a function called `load_annoataion(p)` (there is a typo), you may modify it to fit your data set :)

**Comment by dheeru999** [comment]
in icdar.py, load_annotation(p) 

can you please explain ,what we need to modify to fit the data ?
