### ISSUE TITLE
can't compile lnms on windows

### ISSUE THREAD

**Issue by db2010** [argman/EAST#39]
楼主，您好，我在windows下运行python run_demo_server.py,出现error：
image
![image](https://user-images.githubusercontent.com/20331413/30385178-ed2c3cae-98d8-11e7-8079-6e2d1b3c127d.png)
说是import lnms这儿出错，看了下lanms文件夹下会执行__init__.py的函数
if subprocess.call(['make', '-C', BASE_DIR]) != 0: # return value
raise RuntimeError('Cannot compile lanms: {}'.format(BASE_DIR))
在这个地方出错，楼主知道怎么解决吗？感谢！

**Comment by dotsonliu** [comment]
我也碰到这个问题了，不知如何解决

**Comment by db2010** [comment]
应该是要把adaptor.cpp编译成adaptor.pyd,在linux下直接编译cpp成.so就可以了，但是不知道windows下如何把cpp编译成pyd文件

**Comment by zxytim** [comment]
adaptor.cpp有python头文件就能编译。我用的是pybind11，不是cython

**Comment by dotsonliu** [comment]
@db2010 我微信号 :liudongze1988，最近也在搞east 相互加一下
