### ISSUE TITLE
i directly used to test, positioning are wrong, the effect is poor, is the reason for the training set?

### ISSUE THREAD

**Issue by dotsonliu** [argman/EAST#41]
![image](https://user-images.githubusercontent.com/28289146/30422212-ddea9a9e-9971-11e7-8eea-57665618d338.png)

**Comment by zxytim** [comment]
The model for online demo is trained on only ICDAR2015 and ICDAR 2013, in
which hardly sees Chinese. That's why it works bad on your example.
