### ISSUE TITLE
Text scale

### ISSUE THREAD

**Issue by rmmal** [argman/EAST#44]
I have alot of different text regions with different dimensions and scales , how can i set the parameter "TEXT SCALE" correctly ? 
how can i put the right number ?

and does it depened on the parameter "INPUT SIZE"

**Comment by argman** [comment]
TEXT_SCALE is the max text length EAST can detect, its restricted by the receptive field of CNN. INPUT SIZE is the image size used by training, it should be compatible with TEXT_SCALE, because i think your model should be able to fit all the data used in training.

**Comment by xylcbd** [comment]
what's the meaning of "compatible" in "it should be compatible with TEXT_SCALE"? @argman , thx.

**Comment by xylcbd** [comment]
equals ?
