### ISSUE TITLE
when i run  run_demo_server.py ,i use linux python2.7, there always wrong,  lanms, how can i correct the error?

### ISSUE THREAD

**Issue by dotsonliu** [argman/EAST#45]
![image](https://user-images.githubusercontent.com/28289146/30528442-93db078a-9c65-11e7-89f6-18b43c9df2d4.png)

**Comment by argman** [comment]
try find the python headers and add to the system path

**Comment by dotsonliu** [comment]
@argman can i add your 微信？me: liudongze1988, i use python 2.7 it also has a python3-config error

**Comment by dotsonliu** [comment]
i has located the lib path,but it also error,  ![image](https://user-images.githubusercontent.com/28289146/30530872-ef57f0d4-9c7c-11e7-83c5-30f1fc5e063b.png)

**Comment by argman** [comment]
you can use the python version of nms first.

**Comment by bidai541** [comment]
Change "python3-config" to "python-config" in the Makefile of lanms is ok.

**Comment by billyzju** [comment]
@bidai541 works for me, thank you!
