### ISSUE TITLE
 Score Map Generation

### ISSUE THREAD

**Issue by robotcator** [argman/EAST#5]
In the Section of [3.3.1](http://openaccess.thecvf.com/content_cvpr_2017/papers/Zhou_EAST_An_Efficient_CVPR_2017_paper.pdf), the reference length ri = min(D(pi, p(i mod 4)+1),D(pi, p((i+3) mod 4)+1)). When i = 1, r1 = min(D(p1, p2), D(p1, p1)). So r1 = 0, does it? Can you explain in more detail or which part of code is compute this. Thanks!

**Comment by argman** [comment]
https://github.com/argman/EAST/blob/master/icdar.py#L469

**Comment by robotcator** [comment]
@argman Sorry, I miss the part of code that np.random.rand() > background_ratio. For the part of np.random.rand() < background_ratio, it didn't use generate_rbox(). So the score_map and geo_map are all zero, for what reason to do this?

**Comment by argman** [comment]
it samples background from input images, i think its better for classification.

**Comment by robotcator** [comment]
@argman It seems that [L472](https://github.com/argman/EAST/blob/master/icdar.py#L472)  i is in {0, 1, 2, 3} not as described in paper in {1, 2, 3, 4}. Thank you for the clarification.

**Comment by zxytim** [comment]
@robotcator My apologies for the wrong formula in 3.3.1. It should be i+2 rather than i+3. Please refer to the revised version (v2) of the paper at [https://arxiv.org/pdf/1704.03155v2.pdf](https://arxiv.org/pdf/1704.03155v2.pdf )

**Comment by robotcator** [comment]
@zxytim Thanks, I will look that in detail.
