### ISSUE TITLE
divided by zero, maybe have a try "arctan2"

### ISSUE THREAD

**Issue by ilovin** [argman/EAST#6]
in `icdar.py` , then angle and theta are calculated by `np.arctan`
[L362](https://github.com/argman/EAST/blob/master/icdar.py#L362)
So there exists a risk that value is divided by zero.
I change it to `np.arctan2(dy,-dx)`, it seems works well.

**Comment by zxytim** [comment]
Thanks for reporting. The issue has been fixed.
