### ISSUE TITLE
Why text rectangle generated by my own trained model is always shorter than the text

### ISSUE THREAD

**Issue by whrenstone** [argman/EAST#64]
I have trained EAST model with my own generated text image and text coordinate, the text rectangle generated by my own trained model sometimes is  shorter than the text, but the generated rectangle's height always fits the text's height.
         I have checked the training samples' text rectangle coordinate many times and i am sure it is ok. So i guess the reason may lies in the model's threshold or coefficient, like icdar.py line 221: shrink ratioR = 0.3      
        The trained and result demo is https://github.com/whrenstone/TempImage/tree/master/TestImage
         Could you give me a suggestion? Many thanks! @argman

**Comment by argman** [comment]
see #62

**Comment by whrenstone** [comment]
Thank you very much! I very appreciate it.

**Comment by whrenstone** [comment]
Thank you very much! I very appreciate it. @argman
