### ISSUE TITLE
slim.get_trainable_variables(),

### ISSUE THREAD

**Issue by smuelpeng** [argman/EAST#7]
Hell argman!
My tensorflow version is 1.01. But I encounter the problem as :

`  File "multigpu_train.py", line 135, in main
    variable_restore_op = slim.assign_from_checkpoint_fn(FLAGS.pretrained_model_path, slim.get_trainable_variables(),
AttributeError: 'module' object has no attribute 'get_trainable_variables'
`
And I check tensorflow slim API by Ipython, function"get_trainable_variables" is not available  in  my version.

So, maybe you should consider to upgrade the required TF version.

**Comment by argman** [comment]
thanks for sharing that, maybe its a bug, i am checking it.
