### ISSUE TITLE
GPU usage is zero?

### ISSUE THREAD

**Issue by LearnerInGithub** [argman/EAST#8]
@argman @zxytim  Hi, I find a new problem, the Volatile GPU-Util  is 0 but GPU memory-Usage is about 23 G, and I print the running log, watched that the model load the dataset all the time.  Why the model not do actual computation on GPU?

nvidia-smi Info:
GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M.
5  Tesla M60 24GB      On   | 0000:85:00.0     Off |                  Off |
| N/A   35C    P0    56W / 250W |    23377MiB / 24472MiB |      0%      Default

**Comment by argman** [comment]
I thinks its a tensorflow problem, you can check your tensorflow.

**Comment by zxytim** [comment]
There are some logs about reading images. Please check whether you have encounter some thing like:

> 0 training images in icdar15_training_data
> 0 training images in icdar15_training_data
> 0 training images in icdar15_training_data
> 0 training images in icdar15_training_data
> ...

**Comment by LearnerInGithub** [comment]
my log like this:
1000 training images in icdar15_training_data
1000 training images in icdar15_training_data
1000 training images in icdar15_training_data
1000 training images in icdar15_training_data
After print out 10 lines of such log row, the the model seems suspend, no longer give new output one the command line.  And I locate the the function get_batch() of icdar.py,  I have question about the queue manager codes, not sure whether the problem caused by that.

**Comment by LearnerInGithub** [comment]
@argman Could you share the version of tensorflow you used?

**Comment by zxytim** [comment]
Using the latest source code of master branch (2017-08-04 11:59AM UTF+8)
with tensorflow 1.2.1 works for me.

**Comment by LearnerInGithub** [comment]
My current tensorflow version is also 1.2.1, but it has the above problem...

**Comment by LearnerInGithub** [comment]
@argman @zxytim What python version that you used in this project? python2.7 or python3.0+?

**Comment by zxytim** [comment]
@argman initially uses python 2 and I use python 3.{5,6}. And they should
both work. The newest version should be python{2,3} compatible, as updated
in roadmap: https://github.com/argman/EAST/issues/3

**Comment by stiebels** [comment]
I am facing the same issue. Everything seems to work fine but the computation eventually does not seem to start.
