### ISSUE TITLE
Converting to frozen graph for inference

### ISSUE THREAD

**Issue by Qazi-Farjad** [argman/EAST#85]
Hi,
I am trying to convert the model checkpoint files into the .pb format (i.e. trying to freeze the graph) and cant figure out all the output nodes that are important (Freezing the graph needs input and output nodes).

Can you please enlighten me as to which nodes in the graph are the endpoints/output-nodes ?

**Comment by argman** [comment]
try f_score and f_geometry in [model.py](https://github.com/argman/EAST/blob/master/model.py#L82)

**Comment by Qazi-Farjad** [comment]
so the last concat node and the last conv2d node?
i.e:
feature_fusion/Conv_9/Conv2D
feature_fusion/concat_3

**Comment by Qazi-Farjad** [comment]
f_score comes from the feature_fusion/Conv_7/Sigmoid while f_geometry correlates to the feature_fusion/concat_3 layer. Simply printing the variable gives you the layer names needed.

**Comment by rahul1906** [comment]
@Qazi-Farjad can you send me the commands to export inference graph.

**Comment by kingrain213** [comment]
@Qazi-Farjad there isnt only one feature_fusion/Conv_7/Sigmoid or feature_fusion/concat_3 layer,which should I choose? the last one???

**Comment by Qazi-Farjad** [comment]
Both these names are unique identifiers, so I dont see how you are getting multiple "feature_fusion/Conv_7/Sigmoid"  and "feature_fusion/concat_3" layers.

**Comment by kingrain213** [comment]
@Qazi-Farjad @argman
I used 
print([node.name for node in graph.as_graph_def().node]) 
and found that there are both 2  "feature_fusion/Conv_7/Sigmoid" and "feature_fusion/concat_3" layers, they both starts "model_0" and "model_1" like 
"model_0/feature_fusion/Conv_7/Sigmoid", "model_1/feature_fusion/Conv_7/Sigmoid"
when I put "feature_fusion/Conv_7/Sigmoid" and "feature_fusion/concat_3" layers at output_nodename, it failed with 
assert d in name_to_node_map, "%s is not in graph" % d
AssertionError: feature_fusion/Conv_7/Sigmoid is not in graph

could you show me your freeze code, and test code, which just load the pb model and test one image? my email is 284069003@qq.com thank you 

I just use "model_1/feature_fusion/Conv_7/Sigmoid" and "model_1/feature_fusion/concat_3" layers,but I cant load the pb model and test one image 

thank you very much

**Comment by adeelnasrullah94** [comment]
@kingrain213 
Did you find any solution, I'm facing the same problem here.

**Comment by teemiik** [comment]
could you show the script to run the pb file? my mail teemiik@mail.ru

**Comment by xieyufei1993** [comment]
I can not see both the feature_fusion/Conv_7/Sigmoid and feature_fusion/concat_3
here is my node namse:
feature_fusion/Conv_7/biases (DT_FLOAT) [1]
feature_fusion/Conv_7/biases/Adam (DT_FLOAT) [1]
feature_fusion/Conv_7/biases/Adam_1 (DT_FLOAT) [1]
feature_fusion/Conv_7/biases/ExponentialMovingAverage (DT_FLOAT) [1]
feature_fusion/Conv_7/weights (DT_FLOAT) [1,1,32,1]
feature_fusion/Conv_7/weights/Adam (DT_FLOAT) [1,1,32,1]
feature_fusion/Conv_7/weights/Adam_1 (DT_FLOAT) [1,1,32,1]
feature_fusion/Conv_7/weights/ExponentialMovingAverage (DT_FLOAT) [1,1,32,1]
anyone meet this error?
@adeelnasrullah94 @teemiik @Qazi-Farjad

**Comment by landersaavedra** [comment]
I'm trying to get the words of an energy bill, but I'm not finding the right LAYER, oh you think I should improve the model to work the document. You can helpme, please

**Comment by clair513** [comment]
@landersaavedra If you could share link to your dataset, I could share an implementation with you. Cannot guarantee absolute results but if all your attempts fail, you may reach out (clairds513@gmail.com). Meanwhile, try with the suggestion provided by @Qazi-Farjad. That worked well for me.
Thanks @Qazi-Farjad

**Comment by phamthuha0970** [comment]
I wants to create a model with feature_fusion/Conv_7/Sigmoid and feature_fusion/concat_3 but it isn't feature_fusion/div .What should I do?

**Comment by ehsanro** [comment]
> I wants to create a model with feature_fusion/Conv_7/Sigmoid and feature_fusion/concat_3 but it isn't feature_fusion/div .What should I do?

Did you find any solution?
